name: Build y Deploy AutomÃ¡tico

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener cÃ³digo
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Instalar dependencias
        # Entramos en la carpeta donde realmente estÃ¡ el package.json
        working-directory: ./public_html/dbcocinas
        run: |
          npm install --legacy-peer-deps
          npm install recharts prop-types lucide-react --legacy-peer-deps
          npm install -D vite @vitejs/plugin-react --legacy-peer-deps
          
      - name: 4. Compilar proyecto
        working-directory: ./public_html/dbcocinas
        # Usamos base=./ para que las rutas de los archivos sean relativas
        run: npx vite build --base=./

      - name: 5. ðŸš€ Subir a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPSERVER }}
          username: ${{ secrets.FTPUSER }}
          password: ${{ secrets.FTPPASS }}
          # Ruta local donde Vite genera los archivos
          local-dir: ./public_html/dbcocinas/dist/
          # Ruta en tu servidor Hostinger donde quieres que caigan los archivos
          server-dir: ./public_html/dbcocinas/
          protocol: ftp
          port: 21
